name: qa

on: [push, pull_request]

jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [
          14,
          16,
          18,
        ]
        action: [
          lint,
          test,
          build,
        ]

    steps:
    - uses: actions/checkout@v2
    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    - run: yarn install
    - run: yarn ${{ matrix.action }}

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn audit
